### ISSUE TITLE
Window title bar is missing

### ISSUE THREAD

**Issue by dnchshrp** [Alex313031/ArmCord-Win7#2]
The window title bar is missing

1. Install and try to use ArmCord
2. Realize that window title bar is missing

**Expected behavior**
The title bar should be displayed in order to move/minimize/maximize/close the window

**Screenshots**
![Снимок экрана (6)](https://github.com/Alex313031/ArmCord-Win7/assets/113385003/4d0ea883-b260-409a-9150-4357a1e4323a)

**Desktop (please complete the following information):**
 - OS: Windows 8.1 x64
 - Method of installation: EXE installer
 - Version: 1st Public Release

**Additional context**
-

**Comment by Alex313031** [comment]
@dnchshrp Should be fixed in second release > https://github.com/Alex313031/ArmCord-Win7/releases/tag/v3.3.2

**Comment by Alex313031** [comment]
@dnchshrp Still would occur under some circumstances, like certain themes, should be completely fixed now with an upstream fix added into the works > https://github.com/Alex313031/ArmCord-Win7/commit/8545de1a9b2524dc63fa6972be0cc051d5601eaf

**Comment by Alex313031** [comment]
@dnchshrp > https://github.com/Alex313031/ArmCord-Win7/releases/tag/v3.3.2-1
