### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by the-r3dacted** [Alex313031/ArmCord-Win7#4]
I wanna use ArmCord on multiple computers without needing to move around the folder in AppData.

**Comment by Alex313031** [comment]
@K4sum1 Have you tried the portable .exes?

You might have to use the --user-data-dir=C:\path\to\where\you\want\it flag like in Chromium.

**Comment by the-r3dacted** [comment]
How did I miss that in the download list?

**Comment by the-r3dacted** [comment]
How does this even work? What I want is something that I can pin to taskbar and whatever, and just use a local profile. I tried it and I couldn't figure out where it installed, it seemed to use my AppData profile, and it cleared my QuickCSS.

**Comment by smartfrigde** [comment]
https://github.com/ArmCord/ArmCord/pull/280
If you don't want ArmCord using your AppData folder for storing stuff see this pull request @K4sum1

**Comment by the-r3dacted** [comment]
Interesting, that's a lot like the pmprt.mod style portable mode I added to r3dfox. I didn't think Chromium could have anything similar. Seems to work, only issue seems that it reset my zoom levels but that's an easy fix. Will have to see how it handles moving to another machine.
