### ISSUE TITLE
ArmCord was removed from the Microsoft Store

### ISSUE THREAD

**Issue by mrkrabs206** [Alex313031/ArmCord-Win7#9]
**Describe the bug**

It was removed for no apparent reason from Microsoft Store and now it says “We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available.”.

**To Reproduce**

1. Go to the ArmCord's GitHub
2. Click on **Get it from Microsoft**
3. **Page not found shows up**

**Expected behavior**

Goes to the Store page for ArmCord.

**Screenshots**

![Screenshot_20240708-201013](https://github.com/Alex313031/ArmCord-Win7/assets/110676833/9cfb7a7b-6c4e-4bc9-aebd-517eb82bc366)

**Additional context**
If possible, could you please reupload it? Thank you.

**Comment by smartfrigde** [comment]
Wrong repo + I took it down myself cause Microsoft was holding back my updates. Any reason you rely on Microsoft Store?

**Comment by mrkrabs206** [comment]
Oh

**Comment by mrkrabs206** [comment]
Nothing
